name: Build

on: 
  push:
    branches:
      - main

jobs:
  build:
    name: Build de-csv Project
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4


    - name: Set up Go
      uses: actions/setup-go@v4
  
      with:
        go-version: '1.21.5'

    - name: Build
      run: go build

    - name: Upload artifact
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: de-csv
        path: de-csv
